write inference history to db
hypermodeinc/modus pull request #186
Opened 2024-05-08 19:44 UTC by jairad26

2024-05-10 07:31 UTC, mangalaman93 reviewed
I think, we should work on the structure a bit. Instead of calling db.Initialize, we should call inferenceHistory.Initialize(). And all the code related to inference history can go in that module. I am thinking of this because, right now, we have one inference go routine per entry but we should change that soon to do some sort of batching. Setting up a new connection with the db is also bad. When we change the code, this structure will be useful.

If you want to keep it this way and fix later, that is fine too.

2024-05-13 23:00 UTC, mattjohnsonpint requested changes

2024-05-20 17:24 UTC, mangalaman93 requested changes

2024-05-21 16:01 UTC, mangalaman93 approved these changes

2024-05-21 16:02 UTC, mangalaman93 requested changes

2024-05-21 16:14 UTC, mangalaman93 submitted a review, later dismissed

2024-05-23 16:38 UTC, mattjohnsonpint approved these changes

2024-05-23 16:46 UTC, merged