Jairus/hyp 960 unit tests for plugin transform
hypermodeinc/modus pull request #659
Opened 2024-12-19 19:05 UTC by JairusSW

**Implement tests for AssemblyScript SDK transform**

I implemented a basic test suite using node's builtin testing library which provided basic testing for the ASC Transform.

**Checklist**

- [ x Code compiles correctly and linting passes locally
- [x] For all _code_ changes, an entry added to the `CHANGELOG.md` file describing and linking to this PR
- [x] Tests added for new functionality, or regression tests for bug fixes added as applicable
- [ ] For public APIs, new features, etc., PR on [docs repo](https://github.com/hypermodeinc/docs) staged and linked here

2024-12-22 17:04 UTC, mattjohnsonpint requested changes
Can you please write these in typescript?  Thanks.

2024-12-22 17:04 UTC, mattjohnsonpint commented on CHANGELOG.md
> +- feat: add tests for AssemblyScript SDK Transform [#659](https://github.com/hypermodeinc/modus/pull/659)
```suggestion
- test: add tests for AssemblyScript SDK Transform [#659](https://github.com/hypermodeinc/modus/pull/659)
```

2024-12-22 17:13 UTC, JairusSW commented
@mattjohnsonpint yeah, I can do that
Just have to tweak the tsconfig a bit

2024-12-23 18:13 UTC, JairusSW commented
@mattjohnsonpint I didn't end up compiling the tests to `js` with `tsc`, instead I added node's new `--experimental-strip-types` flag so it can execute the TypeScript files directly
Its experimental, so if you want, I can always switch it back to tsc, just lmk

2024-12-23 18:48 UTC, mattjohnsonpint commented
For tests, the flag is fine as long as it works.  We can always replace it with `tsc` later if fails on anything.

Please add our standard copyright header to the newly added `.ts` files, and then I'll approve.  Thanks.

2024-12-23 19:14 UTC, mattjohnsonpint approved these changes

2024-12-23 19:14 UTC, merged