Jai/hyp 756 support kserve hosted models
hypermodeinc/modus pull request #94
Opened 2024-03-12 02:39 UTC by jairad26

2024-03-12 02:54 UTC, kevinmingtarja requested changes

2024-03-12 17:31 UTC, kevinmingtarja approved these changes

2024-03-12 17:56 UTC, mattjohnsonpint requested changes

2024-03-13 22:17 UTC, mattjohnsonpint approved these changes
LGTM, with exception of the description of the command arg, as mentioned in comments.

2024-03-13 22:20 UTC, mattjohnsonpint approved these changes

2024-03-13 22:21 UTC, merged